#!/bin/bash

## Environtment
export PATH="$HOME/.config/bspwm/bin:${PATH}"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations -------------------------------#
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9'

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config borderless_singleton true
bspc config focus_follows_pointer true

## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2 > code
bspc rule -a Emacs desktop='^2' state=tiled follow=on focus=on

# 3 > web
declare -a browser=(firefox Google-chrome)
for i in ${browser[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on
done

# 4 > chat
declare -a chat=(TelegramDesktop wechat.exe Wine)
for i in ${chat[@]}; do
  bspc rule -a $i desktop='^4' state=floating follow=on focus=on
done

# 5 > media
declare -a media=(Audacity vlc mpv mplayer lxmusic Gimp Gimp-2.8 \
netease-cloud-music)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on
done

# 6 > database
declare -a database=(Mysql-workbench-bin)
for i in ${database[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on
done

# 7 > office
declare -a office=(Geany Leafpad Gucharmap Evince \
Wps Et Wpp Wpspdf libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on
done

# 8 > file
bspc rule -a Pcmanfm desktop='^8' follow=on focus=on

# 9 > settings
bspc rule -a GParted desktop='^9' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 qv2ray \
Xfce4-settings-manager)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^9' state=floating follow=on focus=on
done

# special rules
bspc rule -a Alacritty-float state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a feh state=floating manage=off

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-6+33" -frame_width "1" -font "Iosevka 10" \
-transparency "20" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# Start mpd
exec mpd &

# Fix problems that gray window, applications not resizing with WM, menus immediately closing
wmname LG3D

# Start bspwm scripts
bspcolors
bspcomp
bspbar
bspfcitx5
bspfloat &
